//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRealWorld.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSystemRoleTable
    {
        public int UserSystemRoleID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public int ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual RoleTable RoleTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
