//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRealWorld.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileTable
    {
        public int UserProfileID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public int ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
